version: '3.8'

services:
  db:
    image: mongo
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: test1  # Change to your DB name

  web:
    build: .
    container_name: django_app
    restart: always
    depends_on:
      - db
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - DATABASE_URL=mongodb://db:27017/test1
    command: ["gunicorn", "--bind", "0.0.0.0:8000", "smartquest.wsgi:application"]

volumes:
  mongo_data:
